config/routes.rb
Rails.application.routes.draw do

  resources :orders do
    collection do
      get 'import'
    end
  end

  resources :products do
    collection do
      get 'import'
    end
    resources :variants
  end

  resources :accounts do
    member do
      get 'test_connection'
    end
  end

  get "dashboard/index"
  post "create_contest" => 'dashboard#create_contest'

  root 'dashboard#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  # GET /
  def index

    # Instantiate a new Contest so the form loads properly
    @contest = Contest.new

    # Load past results in reverse order
    @contests = current_account.contests.order("created_at desc")

    # Load the Products we want to use for Contests
    @products = current_account.products.order(:name)

  end

  # This method creates a Contest and returns the winner(s) in the notice message
  def create_contest
    @contest = current_account.contests.new(contest_params)

    respond_to do |format|
      if @contest.save

        # Pick a winner
        candidates = current_account.orders.candidate_list(params)
        contest_results = ContestResults.new(candidates)
        @contest.update_attribute(:order_id,contest_results.results)


        format.html { redirect_to root_path, notice: "Contest Winner: <a href='#{order_path(@contest.order)}'>#{@contest.order.email}</a>" }
        format.json { render action: 'show', status: :created, location: @order }

      else
        format.html { rredirect_to root_path, alert: "Unable to create a Contest" }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end

  end

  # GET /accounts/1/test_connection
  # GET /accounts/1/test_connection.json
  def test_connection
    # Connect to Shopify using our class
    ShopifyIntegration.new(url: current_account.shopify_account_url,
                           password: current_account.shopify_password,
                           account_id: current_account.id).connect()
    begin
      # The gem will throw an exception if unable to retrieve Shop information
      shop = ShopifyAPI::Shop.current
    rescue => ex
      @message = ex.message
    end

    if shop.present?
      respond_to do |format|
        # Report the good news
        format.html { redirect_to dashboard_index_path, notice: "Successfully Connected to #{shop.name}" }
        format.json { render json: "Successfully Connected to #{shop.name}" }
      end
    else
      respond_to do |format|
        # Return the message from the exception
        format.html { redirect_to dashboard_index_path, alert: "Unable to Connect: #{@message}" }
        format.json { render json: "Unable to Connect: #{@message}", status: :unprocessable_entity }
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def contest_params
    params.require(:contest).permit(:name, :product_id, :start_date, :end_date, :max_results, :order_id)
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<%- model_class = Contest -%>
<%- content_for :sidebar do -%>
<h4>New Contest</h4>
<p>Use the form below to run a new Contest. Fields marked with * are required.</p>
  <%= form_for @contest, :url => create_contest_path do |f| %>
    <div class="control-group">
       <%= f.label :name, "Contest Name *"  %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field', :required => true %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :product_id, "Type *" %>
      <div class="controls">
        <select id="contest_product_id" name="contest[product_id]" required="required">
          <option>Any Product</option>
          <optgroup label="Specific Product">
            <%- @products.each do |product| -%>
              <option value="<%= product.shopify_product_id %>"><%= product.name %></option>
            <%- end -%>
          </optgroup>
        </select>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :start_date, "Order Date Range (optional)" %>
      <div class="controls">
        <%= f.text_field :start_date, :class => 'text_field' %>
        <%= f.text_field :end_date, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :max_results, "Max # (optional)" %>
      <div class="controls">
        <%= f.text_field :max_results, :class => 'text_field' %>
      </div>
    </div>
    <div class="form-actions">
      <input type="submit" value="Submit" class="btn"/>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      root_path, :class => 'btn' %>
    </div>
    <!-- End form -->
  <%- end -%>
  <!-- End sidebar -->
<%- end -%>
<h1>Contests</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Criteria</th>
      <th>Winner</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <% @contests.each do |contest| %>
    <tr>
      <td><%= contest.name %></td>
      <td><%= contest.criteria %></td>
      <% if contest.order.present? %>
      <td>Order <%= link_to contest.order.number, order_path(contest.order) %>, <%= contest.order.first_name %> <%= contest.order.last_name %> (<%= mail_to contest.order.email, contest.order.email %>)</td>
      <% else %>
        <td>Error picking winner</td>
      <% end %>
      <td><%=l contest.created_at, format: :long %></td>
    </tr>
    <% end %>
  </tbody>
</table>